#!/bin/bash

case "$1" in
"off" ) brightness=0 ;;
"low" ) brightness=200 ;;
"mid" ) brightness=400 ;;
"max" ) brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness) ;;
* ) echo "Unknown input parameter. Accepted: off/low/mid/max."
    exit 1
    ;;
esac

tee /sys/class/backlight/intel_backlight/brightness <<< "$brightness"
exit 0
